-- Durable reservation/payment-order boundary for Square checkout creation.
--
-- Requires the portal accounts table and migrations through
-- 006-application-document-ledger.sql. Migration 006 adds the required
-- fame_applications(id, market_id) composite key used by the tenant-bound
-- application foreign key below.
-- A future CHECK/RESERVE writer is the only component allowed to insert a
-- `fame_reservations` row. The checkout HTTP route never accepts price,
-- currency, date, vendor, or quantity fields from a caller: it reads the
-- committed reservation below while holding its row lock.
--
-- This migration deliberately supports Sandbox only. Do not loosen the
-- environment check for live payments without a separately reviewed release.
BEGIN;

CREATE TABLE IF NOT EXISTS fame_reservations (
  id TEXT PRIMARY KEY,
  market_id TEXT NOT NULL REFERENCES accounts(id),
  application_id TEXT,
  revision INTEGER NOT NULL CHECK (revision >= 1),
  state TEXT NOT NULL CHECK (state IN (
    'held', 'payment_pending', 'paid', 'confirmed', 'expired',
    'cancelled', 'declined', 'manual_review'
  )),
  payment_required BOOLEAN NOT NULL,
  currency TEXT NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
  total_cents BIGINT NOT NULL CHECK (total_cents >= 0),
  -- This is generated by CHECK/RESERVE from trusted, final quote data. It is
  -- intentionally not supplied by the checkout request or a browser.
  checkout_description TEXT NOT NULL CHECK (char_length(checkout_description) BETWEEN 1 AND 255),
  quote_version TEXT NOT NULL CHECK (char_length(quote_version) BETWEEN 1 AND 192),
  final_booth_quantity INTEGER NOT NULL CHECK (final_booth_quantity >= 1),
  final_dates JSONB NOT NULL,
  payment_request_sent_at TIMESTAMPTZ,
  payment_due_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (id, market_id),
  FOREIGN KEY (application_id, market_id)
    REFERENCES fame_applications(id, market_id),
  CHECK (
    (payment_required AND total_cents > 0)
    OR (NOT payment_required AND total_cents = 0)
  ),
  CHECK (jsonb_typeof(final_dates) = 'array' AND jsonb_array_length(final_dates) > 0)
);

CREATE INDEX IF NOT EXISTS fame_reservations_payment_state_idx
  ON fame_reservations(market_id, state, payment_due_at);

CREATE TABLE IF NOT EXISTS fame_payment_orders (
  id TEXT PRIMARY KEY,
  market_id TEXT NOT NULL REFERENCES accounts(id),
  reservation_id TEXT NOT NULL,
  reservation_revision INTEGER NOT NULL CHECK (reservation_revision >= 1),
  -- The verified identity returned by Square is saved here. An optional
  -- environment merchant ID is a mismatch guard only; it is not trusted as
  -- the source of this value.
  square_environment TEXT NOT NULL CHECK (square_environment = 'sandbox'),
  square_merchant_id TEXT NOT NULL,
  square_location_id TEXT NOT NULL,
  expected_currency TEXT NOT NULL CHECK (expected_currency = 'USD'),
  expected_total_cents BIGINT NOT NULL CHECK (expected_total_cents > 0),
  idempotency_key TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'pending_checkout' CHECK (status IN (
    'pending_checkout', 'processing_checkout', 'checkout_created', 'paid',
    'expired', 'cancelled', 'manual_review', 'failed'
  )),
  square_payment_link_id TEXT,
  square_order_id TEXT,
  checkout_url TEXT,
  payment_id TEXT,
  payment_status TEXT,
  -- Provider timestamps are immutable ordering evidence for webhook handling.
  -- They are distinct from our receipt timestamp and never come from a browser.
  payment_provider_created_at TIMESTAMPTZ,
  payment_provider_updated_at TIMESTAMPTZ,
  payment_received_at TIMESTAMPTZ,
  payment_request_sent_at TIMESTAMPTZ,
  payment_due_at TIMESTAMPTZ,
  checkout_attempts INTEGER NOT NULL DEFAULT 0 CHECK (checkout_attempts >= 0),
  locked_until TIMESTAMPTZ,
  lease_token TEXT,
  last_error_code TEXT,
  failed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (reservation_id, reservation_revision),
  UNIQUE (square_environment, square_merchant_id, square_location_id, square_order_id),
  UNIQUE (square_environment, square_merchant_id, payment_id),
  FOREIGN KEY (reservation_id, market_id)
    REFERENCES fame_reservations(id, market_id),
  CHECK (
    status <> 'checkout_created'
    OR (square_payment_link_id IS NOT NULL AND square_order_id IS NOT NULL AND checkout_url IS NOT NULL)
  ),
  CHECK (
    payment_request_sent_at IS NULL
    OR (square_payment_link_id IS NOT NULL AND square_order_id IS NOT NULL AND checkout_url IS NOT NULL)
  ),
  CHECK (status <> 'paid' OR payment_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS fame_payment_orders_checkout_ready_idx
  ON fame_payment_orders(status, payment_due_at, created_at)
  WHERE status IN ('pending_checkout', 'processing_checkout');

CREATE INDEX IF NOT EXISTS fame_payment_orders_square_order_idx
  ON fame_payment_orders(square_environment, square_merchant_id, square_location_id, square_order_id)
  WHERE square_order_id IS NOT NULL;

COMMIT;
